version: '3.8'
services:

  tailscaled:
    container_name: tailscaled
    user: "0:0"
    privileged: true
    cap_add:
        - NET_ADMIN
    volumes:
        - '/nfs/tailscale/SettingsFolder:/var/lib'
        - '/dev/net/tun:/dev/net/tun'
    network_mode: "host"
    image: tailscale/tailscale
    command: 
        - tailscaled
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TS_USERSPACE=true
      - TS_AUTH_KEY=$tailscale_auth_key
      - TS_ROUTES=192.168.3.0/24
secrets:
  tailscale_auth_key:
    external: true