version: '3.6'

services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
    networks:
      - socket-proxy-net

  traefik:
      image: traefik
      container_name: traefik
      ports:
        - 80:80
        - 443:443
      volumes:
        - /nfs/traefik/logs:/logs
        - /nfs/traefik/configuration/:/configuration/
        #- /var/run/docker.sock:/var/run/docker.sock:ro
        - /nfs/traefik/traefik.yml:/traefik.yml
        - /nfs/traefik/certs:/certs
      restart: unless-stopped
      labels:
        - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
        - "traefik.http.routers.traefik_https.rule=Host(`traefik.lab.local`)" # <== Setting the domain for the dashboard
        - "traefik.http.routers.traefik_https.entrypoints=web,websecure"
        - "traefik.http.routers.traefik_https.service=api@internal"
        - "traefik.http.routers.traefik_https.tls=true"
        - "traefik.http.routers.traefik_https.middlewares=basic-auth-global"
        - "traefik.http.middlewares.basic-auth-global.basicauth.usersfile=/certs/users"
      networks:
        traefik-net:
          # Static IP. Some services need to "trust" the proxy via IP.
          ipv4_address: 172.27.0.12
        # Socket proxy to mitigate risk of someone taking over host machine by taking over traefik.
        socket-proxy-net:
      extra_hosts:
        - host.docker.internal:172.17.0.1
networks:
  traefik-net:
    external: true
  socket-proxy-net:
    